version: '2'
services:
    dev:
        environment:
          - SERVER:${SERVER}
          - PASS=${PASS}
          - EMAIL=${EMAIL}
        build:
          context: ./
          dockerfile: ./build/Dockerfile
        image: api-contactor-parser:latest
        container_name: api-contactor-parser-latest
        volumes:
            - ./:/app
        ports:
          - 8000:8000
        command: gunicorn -w 2 --bind 0.0.0.0:8000 app:app