version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            echo "Building Docker image..."
            docker build -t api-contactor-parser -f ./build/Dockerfile .

  test:
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            echo "This is a placeholder for tests. No actual tests are being run."

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
